const { exec, spawn } = require('child_process');
const fs = require('fs');
const path = require('path');
const settings = require('../settings');
const isOwnerOrSudo = require('../lib/isOwner');

// ─────────────────────────────────────────────────────────────────────────
// PROTECTED PATHS — never touched by an update.
// Anything matching (case-insensitive on the FIRST path segment) is skipped
// when copying the new release on top of the install.
// ─────────────────────────────────────────────────────────────────────────
const PROTECTED_PATHS = new Set([
    // package manager / VCS
    'node_modules', '.git', '.gitignore',
    // env / secrets
    '.env', '.env.local', '.env.production', '.env.development',
    // user-customised configuration (NEVER overwrite — the user's tokens,
    // owner number, branch, zip url, giphy key etc. live here)
    'settings.js', 'config.js',
    // user data — the previous version had only "data" and missed
    // "Database" (capital D), wiping userGroupData.json on every update.
    'data', 'database', 'Database',
    // baileys / pairing / auth — losing these forces a re-pair
    'session', 'sessions', 'auth_info', 'auth_info_baileys',
    'creds.json', 'pairing.json', 'baileys_store.json',
    // backups & runtime state
    'message_backup.json', 'tmp', 'temp',
    // user-customised media (custom menu image / banner)
    'assets',
    // platform metadata that the user may have edited
    '.replit', 'replit.nix', 'replit.md',
    // package-lock will be regenerated by npm install
    'package-lock.json',
]);

const PROTECTED_LC = new Set([...PROTECTED_PATHS].map(p => p.toLowerCase()));

function isProtected(name) {
    return PROTECTED_LC.has(name.toLowerCase());
}

function run(cmd, opts = {}) {
    return new Promise((resolve, reject) => {
        exec(cmd, { windowsHide: true, ...opts }, (err, stdout, stderr) => {
            if (err) return reject(new Error((stderr || stdout || err.message || '').toString()));
            resolve((stdout || '').toString());
        });
    });
}

function makeProgress(sock, chatId, message) {
    // Per-invocation state (the previous version used a module-level
    // `progressMsg`, which raced when two updates ran concurrently).
    let progressMsg = null;
    return async function updateProgress(text) {
        try {
            if (progressMsg) {
                await sock.sendMessage(chatId, { text, edit: progressMsg.key });
            } else {
                progressMsg = await sock.sendMessage(chatId, { text }, { quoted: message });
            }
        } catch (_) { /* ignore — progress is best-effort */ }
    };
}

async function hasGitRepo() {
    if (!fs.existsSync(path.join(process.cwd(), '.git'))) return false;
    try { await run('git --version'); return true; } catch { return false; }
}

async function updateViaGit(reportProgress) {
    await reportProgress('🔄 Git: fetching...');
    const oldRev = (await run('git rev-parse HEAD').catch(() => 'unknown')).trim();
    await run('git fetch --all --prune');

    const branch = (settings.updateBranch || 'main').trim();
    const newRev = (await run(`git rev-parse origin/${branch}`)).trim();
    if (oldRev === newRev) return { alreadyUpToDate: true, oldRev, newRev };

    await reportProgress(`📥 ${oldRev.substring(0, 7)} → ${newRev.substring(0, 7)}`);

    // SAFE pull: stash any local changes (so .env / settings.js edits survive),
    // fast-forward only (no destructive --hard reset), then pop the stash back.
    // Critically: NO `git clean -fd`, which the old version used and which
    // wipes every untracked user-data file.
    let stashed = false;
    try {
        const stashOut = await run('git stash push -u -m "auto-update-stash"').catch(() => '');
        stashed = !/No local changes/i.test(stashOut);
    } catch (_) { /* ignore */ }

    try {
        await run(`git pull --ff-only origin ${branch}`);
    } catch (e) {
        // Couldn't fast-forward (probably divergent history). Hard-reset to
        // the new tip but DO NOT clean — protected files are untracked and
        // must survive.
        await run(`git reset --hard origin/${branch}`);
    }

    if (stashed) {
        try { await run('git stash pop'); } catch (_) { /* conflicts — leave stash */ }
    }

    return { alreadyUpToDate: false, oldRev, newRev };
}

async function extractZip(zipPath, outDir, reportProgress) {
    await reportProgress('📂 Extracting...');
    if (process.platform === 'win32') {
        await run(`powershell -NoProfile -Command "Expand-Archive -Path '${zipPath}' -DestinationPath '${outDir.replace(/\\/g, '/')}' -Force"`);
        return;
    }
    for (const cmd of [
        `unzip -o '${zipPath}' -d '${outDir}'`,
        `7z x -y '${zipPath}' -o'${outDir}'`,
        `busybox unzip -o '${zipPath}' -d '${outDir}'`,
    ]) {
        try { await run(cmd); return; } catch { /* try next */ }
    }
    throw new Error('No unzip tool available');
}

function downloadFile(url, dest, reportProgress, visited = new Set()) {
    return new Promise((resolve, reject) => {
        if (visited.has(url) || visited.size > 5) return reject(new Error('Too many redirects'));
        visited.add(url);

        const token = settings.updateZipToken || process.env.UPDATE_ZIP_TOKEN;
        const headers = { 'User-Agent': 'Adevos-X-Updater/2.0', 'Accept': '*/*' };
        if (token) headers['Authorization'] = `token ${token}`;

        const client = url.startsWith('https://') ? require('https') : require('http');
        const req = client.get(url, { headers }, res => {
            if ([301, 302, 303, 307, 308].includes(res.statusCode)) {
                const next = res.headers.location;
                if (!next) return reject(new Error(`HTTP ${res.statusCode} without Location`));
                res.resume();
                return downloadFile(new URL(next, url).toString(), dest, reportProgress, visited).then(resolve, reject);
            }
            if (res.statusCode !== 200) return reject(new Error(`HTTP ${res.statusCode}`));

            const total = parseInt(res.headers['content-length'], 10);
            let received = 0, lastBucket = 0;
            const file = fs.createWriteStream(dest);
            res.on('data', chunk => {
                received += chunk.length;
                if (total) {
                    const pct = Math.floor((received / total) * 100);
                    if (pct >= lastBucket + 25) {
                        lastBucket = pct;
                        reportProgress(`⬇️ ${pct}%`).catch(() => {});
                    }
                }
            });
            res.pipe(file);
            file.on('finish', () => file.close(resolve));
            file.on('error', err => { try { file.close(() => {}); } catch {} fs.unlink(dest, () => reject(err)); });
        });
        req.on('error', err => fs.unlink(dest, () => reject(err)));
    });
}

// SAFE recursive copy: skips any first-segment match in PROTECTED_PATHS.
// Returns the list of files actually copied.
function safeCopy(src, dest, copied = [], rel = '') {
    if (!fs.existsSync(dest)) fs.mkdirSync(dest, { recursive: true });
    for (const entry of fs.readdirSync(src)) {
        const segment = rel === '' ? entry : rel.split('/')[0];
        if (rel === '' && isProtected(entry)) continue;
        // Also block any nested path whose top segment is protected (defence
        // in depth — should never trigger because we already skipped above).
        if (isProtected(segment)) continue;

        const s = path.join(src, entry);
        const d = path.join(dest, entry);
        const stat = fs.lstatSync(s);
        if (stat.isDirectory()) {
            safeCopy(s, d, copied, rel === '' ? entry : `${rel}/${entry}`);
        } else {
            try {
                fs.copyFileSync(s, d);
                copied.push(rel === '' ? entry : `${rel}/${entry}`);
            } catch (_) { /* skip uncopyable */ }
        }
    }
    return copied;
}

async function updateViaZip(reportProgress, zipOverride) {
    await reportProgress('🗜️ ZIP update starting...');
    const zipUrl = (zipOverride || settings.updateZipUrl || process.env.UPDATE_ZIP_URL || '').trim();
    if (!zipUrl) throw new Error('No updateZipUrl configured in settings.js');

    const tmpDir = path.join(process.cwd(), 'tmp');
    if (!fs.existsSync(tmpDir)) fs.mkdirSync(tmpDir, { recursive: true });

    const zipPath = path.join(tmpDir, 'update.zip');
    await downloadFile(zipUrl, zipPath, reportProgress);

    const extractTo = path.join(tmpDir, 'update_extract');
    if (fs.existsSync(extractTo)) fs.rmSync(extractTo, { recursive: true, force: true });

    await extractZip(zipPath, extractTo, reportProgress);
    await reportProgress('📋 Copying (protected files preserved)...');

    // GitHub-style zips have a single top-level "<repo>-<branch>" wrapper dir.
    const top = fs.readdirSync(extractTo);
    const srcRoot = (top.length === 1 && fs.lstatSync(path.join(extractTo, top[0])).isDirectory())
        ? path.join(extractTo, top[0])
        : extractTo;

    const copied = safeCopy(srcRoot, process.cwd());
    await reportProgress(`✅ Copied ${copied.length} files`);

    try { fs.rmSync(extractTo, { recursive: true, force: true }); } catch {}
    try { fs.rmSync(zipPath, { force: true }); } catch {}
    return { copiedFiles: copied };
}

// ─────────────────────────────────────────────────────────────────────────
// Robust restart. The old version only tried `pm2 restart all` and silently
// fell through to `process.exit(0)`. On panels that don't run pm2 AND don't
// auto-restart on exit, that meant the bot was just GONE.
//
// Strategy now (in priority order):
//   1. If pm2 is genuinely available, use it (returns immediately).
//   2. Otherwise spawn a detached child running the same `node index.js`
//      with stdio:'ignore' and unref(), so the new process is alive BEFORE
//      we exit. Even on a panel without auto-restart, the bot stays up.
//   3. Exit with code 0 so any panel-level supervisor that DOES auto-restart
//      will treat it as a clean restart (not a crash → no backoff).
// ─────────────────────────────────────────────────────────────────────────
async function restartProcess(reportProgress) {
    await reportProgress('♻️ Restarting...');

    // 1. Try pm2 (only if it actually exists on PATH)
    try {
        await run('pm2 --version');
        await run('pm2 restart all');
        return; // pm2 will replace this process
    } catch { /* pm2 not installed — fall through */ }

    // 2. Spawn detached fresh process
    try {
        const node = process.execPath;
        const entry = path.join(process.cwd(), 'index.js');
        const args = fs.existsSync(entry) ? [entry] : process.argv.slice(1);
        const child = spawn(node, args, {
            cwd: process.cwd(),
            detached: true,
            stdio: 'ignore',
            env: process.env,
        });
        child.unref();
        console.log(`[update] spawned fresh process pid=${child.pid}`);
    } catch (e) {
        console.log('[update] could not spawn fresh process:', e.message);
    }

    // 3. Give the spawn a moment to actually start, then exit cleanly
    setTimeout(() => process.exit(0), 1500);
}

async function updateCommand(sock, chatId, message, zipOverride) {
    const senderId = message.key.participant || message.key.remoteJid;
    const isOwner = await isOwnerOrSudo(senderId, sock, chatId);
    if (!message.key.fromMe && !isOwner) {
        await sock.sendMessage(chatId, { text: '❌ Only bot owner can use .update' }, { quoted: message });
        return;
    }

    const reportProgress = makeProgress(sock, chatId, message);
    const startedAt = Date.now();

    try {
        await reportProgress('🔄 Starting update...\n(Protected: .env, settings.js, Database/, assets/, sessions, baileys_store.json)');

        let result;
        if (await hasGitRepo()) {
            result = await updateViaGit(reportProgress);
            if (result.alreadyUpToDate) {
                await reportProgress(`✅ Already up to date (${result.newRev.substring(0, 7)})`);
                return;
            }
        } else {
            await reportProgress('⚠️ No git repo — using ZIP update');
            await updateViaZip(reportProgress, zipOverride);
        }

        await reportProgress('📦 Installing dependencies...');
        try {
            await run('npm install --no-audit --no-fund --omit=optional', { cwd: process.cwd() });
        } catch (e) {
            // npm install failure shouldn't kill the bot — log it but still restart
            console.log('[update] npm install warning:', e.message);
            await reportProgress('⚠️ npm install had issues — restarting anyway');
        }

        const elapsed = ((Date.now() - startedAt) / 1000).toFixed(1);
        const v = (() => { try { delete require.cache[require.resolve('../settings')]; return require('../settings').version || 'unknown'; } catch { return 'unknown'; } })();
        await reportProgress(`✅ Update complete (${elapsed}s) v${v}\n♻️ Restarting now — bot will respond again in ~5s`);

        await restartProcess(reportProgress);

    } catch (err) {
        console.error('[update] failed:', err);
        await reportProgress(`❌ Update failed: ${(err.message || 'unknown').substring(0, 120)}\n(bot is still running — no data was lost)`);
    }
}

module.exports = updateCommand;
